### ISSUE TITLE
Automated download of databases

### ISSUE THREAD

**Issue by ahmedmagds** [ahmedmagds/WhatsGNU#1]
As per discussion with @rpetit3 for inclusion of WhatsGNU in [bactopia](https://github.com/bactopia/bactopia), integration of database auto download into WhatsGNU is needed (e.g. whatsgnu_db_download k_pneumo, whatsgnu_db_download saureus).

**Comment by rpetit3** [comment]
Great! This would make things much easier on the Bactopia side. I like the idea of the links being maintained on the WhatsGNU side, in case they change in the future a simple version update would fix it.

Here's what I started: https://github.com/bactopia/bactopia/blob/master/tools/whatsgnu/main.nf#L7-L31

Leads to this: https://github.com/bactopia/bactopia/blob/master/tools/whatsgnu/main.nf#L55-L62

On the Bactopia Tool side i was planning something like:
```
bactopia tool whatsgnu --whatsgnu_db "saureus_ortho" 
```

Where `--whatsgnu_db` could be a term that downloads one of your DBs or a DB the user already has.
