### ISSUE TITLE
WhatsGNU_main.py Killed

### ISSUE THREAD

**Issue by ZoseJapata** [ahmedmagds/WhatsGNU#2]
Hello, 
I've been hoping to use WhatsGNU_main.py to identify the top 10 genomes with HITS for a sample input. 
I've just had an issue with the program being killed after running the following command: 
WhatsGNU_main.py -d Sau_Staphopia_basic_43914.pickle -dm ortholog -t sample1.faa

Is there anything I can do to fix this?

Thank you if you're able to help!!

**Comment by ahmedmagds** [comment]
@ZoseJapata Sure! It will be helpful to know the error reported. However, I see that you are using the Staphopia database but with the ortholog mode. The Staphopia database is only available in basic mode so this will cause error for sure. Happy to help further if you have any other questions.

**Comment by ZoseJapata** [comment]
Hello! Thank you! 
I swapped it to basic mode and below is what is reported when I try and run the program:
(WhatsGNU) [user@argon-itf-login-3 2Feb2024WhatsGNU_ST398Isolates]$ WhatsGNU_main.py -d Sau_Staphopia_basic_43914.pickle -dm basic -t sample1.faa
2024-02-06 10:03:53,962:INFO:created results folder(WhatsGNU_results_20240206_100353/)
2024-02-06 10:03:53,962:INFO:You provided one faa file as a query
Killed

The .log file created also only states the following: 
2024-02-06 10:03:53,962:INFO:created results folder(WhatsGNU_results_20240206_100353/)
2024-02-06 10:03:53,962:INFO:You provided one faa file as a query

I had tried inputting multiple samples thinking that the INFO was needing more than one query but received the following error:
WhatsGNU_main.py: error: unrecognized arguments: sample2.faa sample3.faa

Would you recommend performing any other actions to try and resolve the error/killing of the run?

**Comment by ahmedmagds** [comment]
@ZoseJapata 
I am worried that you may not have enough memory and specs of your computer. Could you please let me know your memory on the device your are using? it could be also a good idea to try the [Staphylococcus aureus](https://www.dropbox.com/sh/p292mia4oc99hx6/AACPuv7uoYUkZ1WCBDX0XPSVa?dl=0) in ortholog mode instead of Staphopia.

**Comment by ZoseJapata** [comment]
Hello!
I'm so sorry, but I think the issue was the computer specs and memory!
I was able to get it to work using the basic mode when I sent it off to another computer!

Thank you so much for the help!!

**Comment by ahmedmagds** [comment]
Always happy to help!
